### ISSUE TITLE
Design and Build a Privacy Page

### ISSUE THREAD

**Issue by pjatx** [Corona-Trace/coronatrace.org#12]
### Original Slack: 
We do need to get a Privacy page up

#### From tarun

12:37
With a link to the Privacy Policy

12:39
Privacy Principles:
1. Privacy-first
1. you own your data
1. the only way we will use the data is life-saving health notifications.
1. Data is deleted in 10 days.
1. We don’t collect your name, email, phone, device ID - only what is needed to send you a push notification.

#### Current Working Document: 
https://docs.google.com/document/d/1EGXxojfMq3Rd98a-4byi4cJDm2qMa6Elj6iTTLqGJIs/edit

**Comment by Briancmiller** [comment]
URL should be /lega/privacy-policy/

Copy is attached.
[CoronaTrace Privacy Policy (04.02.2020).docx](https://github.com/Corona-Trace/coronatrace.org/files/4429135/CoronaTrace.Privacy.Policy.04.02.2020.docx)

**Comment by pjatx** [comment]
![large (1440 — 1919)](https://user-images.githubusercontent.com/5004634/79367586-bcfc9f00-7f13-11ea-9a08-acd4249a31bd.jpg)
