### ISSUE TITLE
Build beta landing page

### ISSUE THREAD

**Issue by pjatx** [Corona-Trace/coronatrace.org#15]
We need somewhere to send invited beta users to start the signup process.

## Acceptance Criteria: 
- [x] Create duplciate beta landing page and link out to typeform
- [x] Make a decision on where to add security language (landing page / typform / email / somewhere else
- [x] Add security language to landing page if necessary
- [x] Get approval

**Comment by judsonlmoore** [comment]
We are using Mailchimp now instead of Typeform.

**Comment by pjatx** [comment]
Yea this is already done
