### ISSUE TITLE
Add an email capture form the the website

### ISSUE THREAD

**Issue by thenickevans** [Corona-Trace/coronatrace.org#20]
AC:
- [x] Design below
- [x] User should enter the following information: 
    - [x] State
    - [x] Email Address
- [x] Data should be stored somewhere
- [x] They should be added to a mailchimp list based on that data
- [x] Depending on whether or not the state is currently active, we should display a different message that sets expectations
    - [ ] Sorry, it's not avaialbe in your area - we'll email you when it is
    - [ ] Download it now! Show ios and android download buttons

**Comment by pjatx** [comment]
Preivew without state by state logic (we don't have this yet) is done and can be reviewed here: https://5e93269147c411000638c2a4--pensive-pike-fa3f5a.netlify.com/
