### ISSUE TITLE
Update Terms of Service page with new content

### ISSUE THREAD

**Issue by Briancmiller** [Corona-Trace/coronatrace.org#31]
We need to publish the terms of service content. 

At [https://www.coronatrace.org/legal/terms-of-service/](https://www.coronatrace.org/legal/terms-of-service/)

Replace the current "Coming Soon" content with the content in this google doc:
[https://docs.google.com/document/d/1zk-5NZlFTDd_CqBNmlAv7YL8XiZ15mtVDM9KwK1rANM/](https://docs.google.com/document/d/1zk-5NZlFTDd_CqBNmlAv7YL8XiZ15mtVDM9KwK1rANM/)

#17

**Comment by pjatx** [comment]
Thanks! Will get on this ASAP.

**Comment by pjatx** [comment]
@Briancmiller this is done
