### ISSUE TITLE
Add new logo to Contributors page: Interlock

### ISSUE THREAD

**Issue by Briancmiller** [Corona-Trace/coronatrace.org#33]
Please add a logo for a new contributor, Interlock

On https://www.coronatrace.org/contributors/

Under Core Contributors - below BoltSource logo

Add the attached logo.
![Interlock Full Logo - RGB - Color Dark](https://user-images.githubusercontent.com/16547945/78921109-06537700-7a5a-11ea-9d1d-706f3af94a78.jpg)

**Comment by pjatx** [comment]
@Briancmiller any chance you can get an svg?

**Comment by Briancmiller** [comment]
[Interlock Full Logo - RGB - Color Dark.svg.zip](https://github.com/Corona-Trace/coronatrace.org/files/4462588/Interlock.Full.Logo.-.RGB.-.Color.Dark.svg.zip)

Here you are @pjatx.  I also have .ai (used an online converter to make the svg) and .eps.

**Comment by pjatx** [comment]
awesome, thanks much @Briancmiller
