### ISSUE TITLE
Contributors Page with Only Core Contributors

### ISSUE THREAD

**Issue by thenickevans** [Corona-Trace/coronatrace.org#7]
For now, until we release some press on what companies and people are participating, we would like to deploy the Contributors page with only the Core Contributors visible (and not Corporate Sponsors or Individual Contributors).

One way to do this without requiring a code change would be some logic that if the AirTable isn't populated then the section is hidden. That way anyone can go in later and populate the AirTable to have the Corporate Sponsors and Individual Contributors appear.

**Comment by pjatx** [comment]
@thenickevans done!
